# Generated by Django 4.0.4 on 2022-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='txid',
            field=models.CharField(blank=True, default=None, editable=False, max_length=256, null=True, unique=True, verbose_name='TXID'),
        ),
    ]
