# Generated by Django 4.0.4 on 2022-05-28 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_state_address_remove_state_rpc_delete_rpc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0002_alter_deposit_txid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='deposit',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_history_deposit', to='wallet.address'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='counterparty',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_history_deposit', to=settings.AUTH_USER_MODEL, verbose_name='Internal CounterParty ID'),
        ),
    ]
