# Generated by Django 4.0.4 on 2022-05-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_deposit_options_alter_deposited_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_time'], 'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposit'},
        ),
        migrations.DeleteModel(
            name='Deposited',
        ),
    ]
