# Generated by Django 4.0.4 on 2022-05-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_alter_deposit_options_delete_deposited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-block_time'], 'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposit'},
        ),
    ]
