# Generated by Django 4.0.4 on 2022-06-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_state_address_remove_state_rpc_delete_rpc_and_more'),
        ('history', '0006_alter_deposit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='request_info',
            field=models.TextField(blank=True, default='', editable=False, null=True, verbose_name='Request Info'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='success_info',
            field=models.TextField(blank=True, default='', editable=False, null=True, verbose_name='Success Info'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='token',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wallet.token'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='token',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wallet.token'),
        ),
    ]
