# Generated by Django 4.0.4 on 2022-06-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_state_address_remove_state_rpc_delete_rpc_and_more'),
        ('history', '0008_deposit_user_withdraw_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Owner of the order', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_history_deposit', to='wallet.address'),
        ),
    ]
