# Generated by Django 4.0.4 on 2022-06-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_remove_deposit_user_alter_deposit_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='uuid',
            field=models.CharField(default=None, editable=False, max_length=64, verbose_name='History UUID'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uuid',
            field=models.CharField(default=None, editable=False, max_length=64, verbose_name='History UUID'),
        ),
    ]
