# Generated by Django 4.0.4 on 2022-05-09 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_name', models.CharField(default='Tron', max_length=32, verbose_name='Chain Name')),
                ('chain_network', models.CharField(max_length=32, verbose_name='Chain Network')),
                ('chain_symbol', models.CharField(default='TRX', max_length=32, verbose_name='Chain Token Symbol')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('explorer_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Explorer URL')),
            ],
            options={
                'verbose_name': 'chain',
                'verbose_name_plural': 'chain',
            },
        ),
        migrations.CreateModel(
            name='Pubkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=128, unique=True, verbose_name='Account Extended Public Key')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('chain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.chain')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_pubkey', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'public key',
                'verbose_name_plural': 'public key',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label/Tag/Memo', max_length=128, null=True, verbose_name='Label')),
                ('index', models.IntegerField(default=0, verbose_name='Inedx')),
                ('address', models.CharField(default='Temporary discontinuation of service', max_length=128, unique=True, verbose_name='address')),
                ('type', models.CharField(choices=[('DEPOSIT', 'deposit'), ('SYSTEM_LEASE', 'system lease')], max_length=32, verbose_name='Address Type')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this address should be treated as active. Unselect this instead of deleting address.', verbose_name='Active')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('chain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_address', to='wallet.chain')),
                ('pubkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_address', to='wallet.pubkey', verbose_name='Public Key')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_address', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Contract Address')),
                ('token_symbol', models.CharField(max_length=32, null=True, verbose_name='Token Symbol')),
                ('token_name', models.CharField(max_length=64, null=True, verbose_name='Token Name')),
                ('token_decimal', models.SmallIntegerField(default=6, verbose_name='Token Decimal')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this address should be treated as active. Unselect this instead of deleting address.', verbose_name='Active')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('chain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.chain')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'unique_together': {('token_symbol', 'contract_address')},
            },
        ),
    ]
