# Generated by Django 4.0.4 on 2022-07-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pubkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_address', to='wallet.pubkey', verbose_name='Public Key'),
        ),
    ]
