# Generated by Django 4.0.4 on 2022-05-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='chain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_address', to='wallet.chain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pubkey',
            name='chain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallet.chain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='chain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallet.chain'),
            preserve_default=False,
        ),
    ]
