# Generated by Django 4.0.4 on 2022-05-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chain',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chain',
            old_name='updated_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='pubkey',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='updated_time',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AddField(
            model_name='pubkey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
    ]
