# Generated by Django 4.0.4 on 2022-05-21 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_address_chain_alter_pubkey_chain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('company', models.CharField(max_length=128, verbose_name='company')),
                ('alias', models.CharField(blank=True, max_length=128, null=True, verbose_name='alias')),
                ('endpoint', models.CharField(max_length=128, verbose_name='endpoint')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('auth', models.CharField(max_length=128, verbose_name='auth')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_rpc', to='wallet.chain')),
            ],
            options={
                'verbose_name': 'RPC',
                'verbose_name_plural': 'RPC',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('balance', models.JSONField(verbose_name='balance')),
                ('next_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_state', to='wallet.address')),
                ('rpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_state', to='wallet.rpc')),
                ('token', models.ManyToManyField(related_name='wallet_state', to='wallet.token')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
