# Generated by Django 4.0.4 on 2022-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_created_time_address_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubkey',
            name='public_key',
            field=models.CharField(max_length=128, verbose_name='Account Extended Public Key'),
        ),
        migrations.AlterUniqueTogether(
            name='pubkey',
            unique_together={('public_key', 'chain')},
        ),
    ]
