# Generated by Django 4.0.4 on 2022-05-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rpc_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpc',
            name='auth',
            field=models.CharField(choices=[('NORMAL', 'normal')], default='NORMAL', max_length=128, verbose_name='auth'),
        ),
    ]
