# Generated by Django 4.0.4 on 2022-05-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_rpc_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_update',
            field=models.BooleanField(default=False, help_text='Status of address update', verbose_name='update'),
        ),
        migrations.AlterField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether it is necessary to detect the operating status of the address', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='state',
            name='next_time',
            field=models.DateTimeField(editable=False, help_text='When to run the next test', verbose_name='Created Time'),
        ),
    ]
