# Generated by Django 4.0.4 on 2022-05-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_state_is_update_alter_state_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='token',
        ),
    ]
