# Generated by Django 4.0.4 on 2022-05-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_state_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='next_time',
            field=models.DateTimeField(auto_now=True, help_text='When to run the next test', verbose_name='Created Time'),
        ),
    ]
