# Generated by Django 4.0.4 on 2022-05-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_state_next_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State', 'verbose_name_plural': 'Status'},
        ),
    ]
