# Generated by Django 4.0.4 on 2022-05-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_state_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='address',
        ),
        migrations.RemoveField(
            model_name='state',
            name='rpc',
        ),
        migrations.DeleteModel(
            name='RPC',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
