# Generated by Django 4.0.4 on 2022-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_state_address_remove_state_rpc_delete_rpc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Fee'),
        ),
    ]
