# Generated by Django 4.0.4 on 2022-06-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_token_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0, help_text='The handling fee is only used as a record and cannot be used as a calculation parameter', max_digits=32, verbose_name='Fee'),
        ),
    ]
