# Generated by Django 4.0.4 on 2022-06-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_token_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_use',
            field=models.BooleanField(default=True, help_text='The address the user is currently using, when set to True, it will be displayed on top', verbose_name='Use'),
        ),
    ]
