# Generated by Django 4.0.4 on 2022-06-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_address_is_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_select',
            field=models.BooleanField(default=True, help_text='The address the user is currently using, when set to True, it will be displayed on top.', verbose_name='Select'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_use',
            field=models.BooleanField(default=False, help_text='Whether the current address has been used, if there is a deposit record, set to True.', verbose_name='Use'),
        ),
    ]
