# Generated by Django 4.0.4 on 2022-05-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0009_remove_state_address_remove_state_rpc_delete_rpc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('company', models.CharField(max_length=128, verbose_name='company')),
                ('alias', models.CharField(blank=True, max_length=128, null=True, verbose_name='alias')),
                ('endpoint', models.CharField(max_length=128, verbose_name='endpoint')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('auth', models.CharField(choices=[('NORMAL', 'normal')], default='NORMAL', max_length=128, verbose_name='auth')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_rpc', to='wallet.chain')),
            ],
            options={
                'verbose_name': 'RPC',
                'verbose_name_plural': 'RPC',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('balance', models.JSONField(verbose_name='balance')),
                ('next_time', models.DateTimeField(auto_now=True, help_text='When to run the next test', verbose_name='Created Time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether it is necessary to detect the operating status of the address', verbose_name='active')),
                ('is_update', models.BooleanField(default=False, help_text='Status of address update', verbose_name='update')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_state', to='wallet.address')),
                ('rpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_state', to='chainstate.rpc')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'Status',
            },
        ),
    ]
