# Generated by Django 4.0.4 on 2022-06-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('company', models.CharField(max_length=128, verbose_name='company')),
                ('alias', models.CharField(blank=True, max_length=128, null=True, verbose_name='alias')),
                ('endpoint', models.CharField(max_length=128, verbose_name='endpoint')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('auth', models.CharField(choices=[('NORMAL', 'normal')], default='NORMAL', max_length=128, verbose_name='auth')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_chainstate_rpc', to='wallet.chain')),
            ],
            options={
                'verbose_name': 'RPC',
                'verbose_name_plural': 'RPC',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('usdt_balance', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='usdt balance')),
                ('stop_at', models.DateTimeField(editable=False, help_text='When to stop the test', verbose_name='Stop Time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether it is necessary to detect the operating status of the address', verbose_name='active')),
                ('is_update', models.BooleanField(default=False, help_text='Status of address update', verbose_name='update')),
                ('query_count', models.IntegerField(default=0, verbose_name='query count')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_chainstate_state', to='wallet.address')),
                ('rpc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_chainstate_state', to='chainstate.rpc')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'Status',
                'ordering': ['-is_active', '-is_update', '-updated_at'],
            },
        ),
    ]
