# Generated by Django 4.0.4 on 2022-05-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_state_address_remove_state_rpc_delete_rpc_and_more'),
        ('chainstate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='next_time',
        ),
        migrations.AddField(
            model_name='state',
            name='stop_at',
            field=models.DateTimeField(auto_now=True, help_text='When to stop the test', verbose_name='Stop Time'),
        ),
        migrations.AlterField(
            model_name='rpc',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_chainstate_rpc', to='wallet.chain'),
        ),
        migrations.AlterField(
            model_name='state',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_chainstate_state', to='wallet.address'),
        ),
        migrations.AlterField(
            model_name='state',
            name='rpc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_chainstate_state', to='chainstate.rpc'),
        ),
    ]
