# Generated by Django 4.0.4 on 2022-07-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_address_pubkey'),
        ('chainstate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('block_number', models.IntegerField(verbose_name='Block Number')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.chain')),
                ('rpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chainstate.rpc')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
