# Generated by Django 4.0.4 on 2022-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainstate', '0002_remove_state_next_time_state_stop_at_alter_rpc_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='stop_at',
            field=models.DateTimeField(editable=False, help_text='When to stop the test', verbose_name='Stop Time'),
        ),
    ]
