# Generated by Django 4.0.4 on 2022-05-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainstate', '0003_alter_state_stop_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='query_count',
            field=models.IntegerField(default=0, verbose_name='query count'),
        ),
    ]
