# Generated by Django 4.0.4 on 2022-05-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainstate', '0004_state_query_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='balance',
        ),
        migrations.AddField(
            model_name='state',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='usdt balance'),
        ),
    ]
