# Generated by Django 4.0.4 on 2022-05-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainstate', '0005_remove_state_balance_state_usdt_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='rpc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_chainstate_state', to='chainstate.rpc'),
        ),
    ]
