# Generated by Django 4.0.4 on 2022-05-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_state_address_remove_state_rpc_delete_rpc_and_more'),
        ('chainstate', '0006_alter_state_rpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_chainstate_state', to='wallet.address'),
        ),
    ]
