# Generated by Django 4.0.4 on 2022-06-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainstate', '0007_alter_state_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['updated_at'], 'verbose_name': 'State', 'verbose_name_plural': 'Status'},
        ),
    ]
