# Generated by Django 4.0.4 on 2022-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainstate', '0008_alter_state_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-is_active', '-is_update', '-updated_at'], 'verbose_name': 'State', 'verbose_name_plural': 'Status'},
        ),
    ]
